# Generated by Django 4.1.1 on 2022-09-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_remove_choice_votes_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.choice"
            ),
        ),
    ]
